### ISSUE TITLE
json editor版本问题

### ISSUE THREAD

**Issue by wzhih** [laravel-admin-extensions/json-editor#6]
能不能更新到最新的`jsoneditor6.2.1`，现在用的是`5.24`，太老了

**Comment by jxlwqq** [comment]
@wzhih 需要用到 6.2 的一些新特性吗

**Comment by wzhih** [comment]
主要是国际化，支持多种语言，另外`jsoneditor`的文档也只有最新的，并没有老版本文档，阅读及其使用不便 @jxlwqq

**Comment by wzhih** [comment]
还有一个问题，不能设置默认值

**Comment by jxlwqq** [comment]
@wzhih 
```bash
composer require jxlwqq/json-editor:dev-master
```
试试，没问题的话，我就发个新版本

**Comment by jxlwqq** [comment]
> 还有一个问题，不能设置默认值

```php
$form->json('content')->default(['1' => 1]);
```
这样不行吗

**Comment by wzhih** [comment]
> > 还有一个问题，不能设置默认值
> 
> ```
> $form->json('content')->default(['1' => 1]);
> ```
> 
> 这样不行吗

我想要传入空object，但是直接`{}`，会识别成`[]`
这个可能是json-editor那边的问题

**Comment by wzhih** [comment]
早上基本使用了一下dev-master，没出现问题

**Comment by jxlwqq** [comment]
好的 我发布一个新的版本
