### ISSUE TITLE
当$json为空的时候，建议不要set(json)了

### ISSUE THREAD

**Issue by wzhih** [laravel-admin-extensions/json-editor#7]
在Editor.php的46-48行，设置了json，但是，当$json为空的时候，渲染出来，文本域里面是数组`[]`,而不是对象`{}`

json editor在json为空的时候，默认显示的是对象

所以建议与json-editor同步，当$json为空的时候，不要set(json)

**Comment by jxlwqq** [comment]
@wzhih 要不你提个pr？我没太理解你的意思。

**Comment by jxlwqq** [comment]
closed by #8
